-- MySQL Script generated by MySQL Workbench
-- 03/11/17 19:18:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test-register
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test-register
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test-register` DEFAULT CHARACTER SET utf8 ;
USE `test-register` ;

-- -----------------------------------------------------
-- Table `test-register`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test-register`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL COMMENT 'Nome do Cliente',
  `cpf` VARCHAR(20) NOT NULL COMMENT 'CPF do Cliente',
  `general_registration` VARCHAR(20) NULL COMMENT 'RG do Cliente',
  `date_of_birth` DATE NOT NULL COMMENT 'Data de nascimento do Cliente',
  `created_at` DATETIME NOT NULL COMMENT 'Data e hora de cadastro do Cliente',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test-register`.`phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test-register`.`phone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `number` VARCHAR(20) NULL,
  PRIMARY KEY (`id`, `client_id`),
  INDEX `fk_phone_client_idx` (`client_id` ASC),
  CONSTRAINT `fk_phone_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `test-register`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test-register`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test-register`.`state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `initial` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test-register`.`configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test-register`.`configuration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `website_name` VARCHAR(60) NOT NULL,
  `version` VARCHAR(10) NULL,
  `state_id` INT NOT NULL,
  PRIMARY KEY (`id`, `state_id`),
  INDEX `fk_configuration_state1_idx` (`state_id` ASC),
  CONSTRAINT `fk_configuration_state1`
    FOREIGN KEY (`state_id`)
    REFERENCES `test-register`.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test-register`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test-register`.`login` (
  `id` INT NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `user` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
